[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'junegunn/fzf'
path = '~/.fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'jreybert/vimagit'

[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'tpope/vim-rhubarb'
